version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby : 2.5.0-node-browsers
        environment:
          RAILS_ENV: test
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
          host: db
      - image: circleci/mysql:5.7
    working_directory: ~/Noxel
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
