version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: "before_test: bundle"
          command: docker-compose run web bundle
      - run:
          name: docker-compose downしないとDBコンテナが間に合わなくてエラーになる
          command: docker-compose down
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: "before_test: setup create"
          command: docker-compose run web rails db:create
      - run:
          name: "before_test: setup migrate"
          command: docker-compose run web rails db:migrate
      - run:
          name: プリコンパイル
          command: docker-compose run web rake assets:precompile
      - run:
          name: test
          command: docker-compose run web rails test
      - run:
          name: docker-compose down
          command: docker-compose down
